import React, { useState } from 'react';
import { Search, Plus, X, ArrowUpDown, ChevronDown } from 'lucide-react';
import light1 from '../assets/product_images/light.png';
import light2 from '../assets/product_images/light2.png';
import light3 from '../assets/product_images/light3.png';
import light4 from '../assets/product_images/light4.png';
import light5 from '../assets/product_images/light5.png';
import light6 from '../assets/product_images/light6.png';
import light7 from '../assets/product_images/light7.png';
import light8 from '../assets/product_images/light8.png';
import light9 from '../assets/product_images/light9.png';
import light10 from '../assets/product_images/light10.png';

import { collection, addDoc, deleteDoc, doc } from "firebase/firestore";
import { db } from "../firebase";

const Products = ({ products, setProducts }) => {
    const [isPopupOpen, setIsPopupOpen] = useState(false);
    const [isSortOpen, setIsSortOpen] = useState(false);
    const [sortConfig, setSortConfig] = useState({ key: 'name', direction: 'asc' });
    const [currentPage, setCurrentPage] = useState(1);
    const ITEMS_PER_PAGE = 10;
    const [newItem, setNewItem] = useState({
        name: '',
        qty: '',
        image: null
    });

    // Derived sorted products
    const sortedProducts = [...products].sort((a, b) => {
        if (sortConfig.key === 'name') {
            return sortConfig.direction === 'asc'
                ? a.name.localeCompare(b.name)
                : b.name.localeCompare(a.name);
        }
        if (sortConfig.key === 'qty') {
            return sortConfig.direction === 'asc'
                ? parseInt(a.qty) - parseInt(b.qty)
                : parseInt(b.qty) - parseInt(a.qty);
        }
        if (sortConfig.key === 'date') {
            // Using ID or index as proxy for date if no createdAt field
            // Assuming newer items have larger/different IDs or just order in array.
            // Ideally use a timestamp field. If none, ID might not differ if random string.
            // If array order represents date added (from Firestore default?), then original index matters.
            // But existing code doesn't preserve index after sort.
            // I'll rely on string comparison of ID for stability or assume random string. 
            // Actually, if we want "Date", we usually mean "Newest First" or "Oldest First".
            // Since we lack a dedicated 'createdAt' field in the fetched data (we didn't map it),
            // I will use alphabetical sort of Name as a placeholder or just ignore?
            // No, I'll use ID comparison, which is stable but maybe not meaningful for Date.
            // Note: User asked for "Date by". I will treat simple string compare of ID for now 
            // OR better: I will update addDoc to include createdAt and use it, but existing data won't have it.
            // Fallback: Use ID string compare.
            return sortConfig.direction === 'asc'
                ? String(a.id).localeCompare(String(b.id))
                : String(b.id).localeCompare(String(a.id));
        }
        return 0;
    });

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setNewItem(prev => ({
            ...prev,
            [name]: value
        }));
    };

    const handleImageChange = (e) => {
        const file = e.target.files[0];
        if (file) {
            // Convert to Base64 for Firestore storage (Note: Large images will fail, Storage is recommended)
            const reader = new FileReader();
            reader.onloadend = () => {
                setNewItem(prev => ({
                    ...prev,
                    image: reader.result
                }));
            };
            reader.readAsDataURL(file);
        }
    };

    const handleAddItem = async () => {
        if (!newItem.name || !newItem.qty || !newItem.image) {
            alert('Please fill all fields and upload an image.');
            return;
        }

        try {
            const newProduct = {
                // id: Generated by Firestore
                name: newItem.name,
                qty: parseInt(newItem.qty),
                image: newItem.image // Base64 string
            };

            const docRef = await addDoc(collection(db, "products"), newProduct);
            console.log("Product written with ID: ", docRef.id);

            setIsPopupOpen(false);
            setNewItem({ name: '', qty: '', image: null });
        } catch (e) {
            console.error("Error adding document: ", e);
            alert("Error adding product");
        }
    };

    const resetForm = () => {
        setNewItem({ name: '', qty: '', image: null });
    };

    const seedData = async () => {
        if (products.length > 0) {
            if (!confirm("Database already has products. Are you sure you want to add duplicate seed data?")) return;
        }

        const initialProducts = [
            { name: 'Item 1', qty: 20, image: light1 },
            { name: 'Item 2', qty: 20, image: light2 },
            { name: 'Item 3', qty: 20, image: light3 },
            { name: 'Item 4', qty: 30, image: light4 },
            { name: 'Item 5', qty: 20, image: light5 },
            { name: 'Item 6', qty: 20, image: light6 },
            { name: 'Item 7', qty: 20, image: light7 },
            { name: 'Item 8', qty: 20, image: light8 },
            { name: 'Item 9', qty: 30, image: light9 },
            { name: 'Item 10', qty: 20, image: light10 },
        ];

        try {
            alert("Starting seeding... please wait.");
            const promises = initialProducts.map(async (item) => {
                // Fetch the image from the local URL
                const response = await fetch(item.image);
                const blob = await response.blob();

                // Convert to Base64
                return new Promise((resolve, reject) => {
                    const reader = new FileReader();
                    reader.onloadend = async () => {
                        const base64data = reader.result;
                        await addDoc(collection(db, "products"), {
                            name: item.name,
                            qty: String(item.qty), // Keeping as string to match previous pattern if needed, or int. App used string '20'.
                            image: base64data
                        });
                        resolve();
                    };
                    reader.onerror = reject;
                    reader.readAsDataURL(blob);
                });
            });

            await Promise.all(promises);
            alert("Database seeded successfully!");
        } catch (error) {
            console.error("Error seeding database:", error);
            alert("Error seeding database. Check console.");
        }
    };

    const clearData = async () => {
        if (!confirm("Are you sure you want to DELETE ALL products from the database? This cannot be undone.")) return;

        try {
            alert("Clearing database... please wait.");
            const promises = products.map(async (product) => {
                await deleteDoc(doc(db, "products", product.id));
            });

            await Promise.all(promises);
            alert("All products deleted successfully!");
        } catch (error) {
            console.error("Error clearing database:", error);
            alert("Error clearing database. Check console.");
        }
    };

    const [searchQuery, setSearchQuery] = useState("");

    const filteredProducts = sortedProducts.filter(product => {
        if (!searchQuery) return true;
        const query = searchQuery.toLowerCase();

        return (
            (product.name && product.name.toLowerCase().includes(query)) ||
            (String(product.qty).includes(query))
        );
    });

    return (
        <div style={styles.container}>
            <div style={styles.titleSection}>
                <h1 style={styles.pageTitle}>Products</h1>
                <div style={styles.titleUnderline}></div>
            </div>

            <div style={styles.controlsBar}>
                <div style={styles.searchWrapper}>
                    <Search size={20} color="#999" style={styles.searchIcon} />
                    <input
                        type="text"
                        placeholder="Search Products"
                        style={styles.searchInput}
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                    />
                </div>

                <div style={{ position: 'relative' }}>
                    <button
                        style={{ ...styles.addButton, backgroundColor: '#f0f0f0', color: 'black', border: '1px solid #ddd', marginRight: '10px' }}
                        onClick={() => setIsSortOpen(!isSortOpen)}
                    >
                        <ArrowUpDown size={18} color="black" />
                        <span style={{ ...styles.addButtonText, color: 'black' }}>Sort By</span>
                        <ChevronDown size={14} color="black" />
                    </button>

                    {isSortOpen && (
                        <div style={styles.sortDropdown}>
                            <div style={styles.sortSection}>
                                <div style={styles.sortLabel}>Type</div>
                                <div
                                    style={{ ...styles.sortOption, backgroundColor: sortConfig.key === 'name' ? '#e6f0ff' : 'transparent' }}
                                    onClick={() => setSortConfig({ ...sortConfig, key: 'name' })}
                                >
                                    Name by
                                </div>
                                <div
                                    style={{ ...styles.sortOption, backgroundColor: sortConfig.key === 'date' ? '#e6f0ff' : 'transparent' }}
                                    onClick={() => setSortConfig({ ...sortConfig, key: 'date' })}
                                >
                                    Date by
                                </div>
                                <div
                                    style={{ ...styles.sortOption, backgroundColor: sortConfig.key === 'qty' ? '#e6f0ff' : 'transparent' }}
                                    onClick={() => setSortConfig({ ...sortConfig, key: 'qty' })}
                                >
                                    Qty by
                                </div>
                            </div>
                            <div style={{ ...styles.sortSection, borderTop: '1px solid #eee' }}>
                                <div style={styles.sortLabel}>Order</div>
                                <div
                                    style={{ ...styles.sortOption, backgroundColor: sortConfig.direction === 'asc' ? '#e6f0ff' : 'transparent' }}
                                    onClick={() => setSortConfig({ ...sortConfig, direction: 'asc' })}
                                >
                                    Ascending
                                </div>
                                <div
                                    style={{ ...styles.sortOption, backgroundColor: sortConfig.direction === 'desc' ? '#e6f0ff' : 'transparent' }}
                                    onClick={() => setSortConfig({ ...sortConfig, direction: 'desc' })}
                                >
                                    Descending
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                <button style={styles.addButton} onClick={() => setIsPopupOpen(true)}>
                    <Plus size={18} color="white" />
                    <span style={styles.addButtonText}>Add Products</span>
                </button>
            </div>

            <div style={styles.gridContainer}>
                {filteredProducts.slice((currentPage - 1) * ITEMS_PER_PAGE, currentPage * ITEMS_PER_PAGE).map((product) => (
                    <div key={product.id} className="product-card">
                        <h3 style={styles.itemName}>{product.name}</h3>
                        <div style={styles.imageContainer}>
                            <img src={product.image} alt={product.name} style={styles.productImage} />
                        </div>
                        <div style={styles.qtyText}>Qty. {product.qty}</div>
                    </div>
                ))}
            </div>

            <div style={styles.pagination}>
                <button
                    style={{ ...styles.pageBtn, opacity: currentPage === 1 ? 0.5 : 1, cursor: currentPage === 1 ? 'not-allowed' : 'pointer' }}
                    onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                    disabled={currentPage === 1}
                >
                    Previous
                </button>

                {Array.from({ length: Math.ceil(filteredProducts.length / ITEMS_PER_PAGE) }, (_, i) => (
                    <button
                        key={i + 1}
                        style={currentPage === i + 1 ? styles.activePageBtn : styles.pageBtn}
                        onClick={() => setCurrentPage(i + 1)}
                    >
                        {i + 1}
                    </button>
                ))}

                <button
                    style={{ ...styles.pageBtn, opacity: currentPage === Math.ceil(filteredProducts.length / ITEMS_PER_PAGE) ? 0.5 : 1, cursor: currentPage === Math.ceil(filteredProducts.length / ITEMS_PER_PAGE) ? 'not-allowed' : 'pointer' }}
                    onClick={() => setCurrentPage(prev => Math.min(prev + 1, Math.ceil(filteredProducts.length / ITEMS_PER_PAGE)))}
                    disabled={currentPage === Math.ceil(filteredProducts.length / ITEMS_PER_PAGE)}
                >
                    Next
                </button>
            </div>

            {isPopupOpen && (
                <div style={styles.popupOverlay}>
                    <div style={styles.popup}>
                        <div style={styles.popupHeader}>
                            <h2 style={styles.popupTitle}>Add New Product</h2>
                            <button onClick={() => setIsPopupOpen(false)} style={styles.closeButton}>
                                <X size={24} color="white" />
                            </button>
                        </div>
                        <div style={styles.popupContent}>
                            <div style={styles.inputGroup}>
                                <label style={styles.label}>Product Name</label>
                                <input
                                    type="text"
                                    name="name"
                                    value={newItem.name}
                                    onChange={handleInputChange}
                                    style={styles.input}
                                    placeholder="Enter product name"
                                />
                            </div>
                            <div style={styles.inputGroup}>
                                <label style={styles.label}>Quantity</label>
                                <input
                                    type="number"
                                    name="qty"
                                    value={newItem.qty}
                                    onChange={handleInputChange}
                                    style={styles.input}
                                    placeholder="Enter quantity"
                                />
                            </div>
                            <div style={styles.inputGroup}>
                                <label style={styles.label}>Product Image</label>
                                <input
                                    type="file"
                                    accept="image/*"
                                    onChange={handleImageChange}
                                    style={styles.fileInput}
                                />
                                {newItem.image && (
                                    <div style={styles.imagePreview}>
                                        <img src={newItem.image} alt="Preview" style={styles.previewImg} />
                                    </div>
                                )}
                            </div>
                            <div style={styles.popupActions}>
                                <button onClick={resetForm} style={styles.resetButton}>Reset</button>
                                <button onClick={handleAddItem} style={styles.submitButton}>Add Product</button>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

const styles = {
    container: {
        padding: '20px 40px',
        maxWidth: '1200px',
        margin: '0 auto',
        width: '100%',
        position: 'relative',
    },
    titleSection: {
        marginBottom: '30px',
        display: 'inline-block',
    },
    pageTitle: {
        fontSize: '32px',
        fontWeight: '700',
        marginBottom: '5px',
        color: '#FFFFFF',
    },
    titleUnderline: {
        height: '3px',
        width: '100%',
        backgroundColor: '#0066CC',
        borderRadius: '2px',
    },
    controlsBar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '30px',
    },
    searchWrapper: {
        display: 'flex',
        alignItems: 'center',
        backgroundColor: 'var(--bg-card)',
        border: '1px solid var(--border-color)',
        borderRadius: '8px',
        padding: '10px 15px',
        width: '300px',
    },
    searchIcon: {
        marginRight: '10px',
    },
    searchInput: {
        border: 'none',
        outline: 'none',
        width: '100%',
        fontSize: '14px',
        color: 'var(--text-main)',
        backgroundColor: 'transparent',
    },
    addButton: {
        backgroundColor: '#0044CC',
        color: 'white',
        border: 'none',
        borderRadius: '8px',
        padding: '10px 20px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        cursor: 'pointer',
        boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    },
    addButtonText: {
        fontWeight: '600',
        fontSize: '14px',
    },
    gridContainer: {
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
        gap: '20px',
        paddingBottom: '40px',
    },
    itemName: {
        fontSize: '16px',
        fontWeight: '700',
        marginBottom: '15px',
        color: 'var(--text-main)',
    },
    imageContainer: {
        height: '120px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: '15px',
    },
    productImage: {
        maxHeight: '100%',
        maxWidth: '100%',
        objectFit: 'contain',
    },
    qtyText: {
        fontSize: '16px',
        fontWeight: '700',
        color: 'var(--text-main)',
    },
    // Popup Styles
    popupOverlay: {
        position: 'fixed',
        top: 0,
        left: 0,
        width: '100%',
        height: '100%',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        backdropFilter: 'blur(5px)',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 1000,
    },
    popup: {
        backgroundColor: 'var(--bg-card)',
        borderRadius: '12px',
        width: '500px',
        maxWidth: '90%',
        boxShadow: '0 4px 20px rgba(0,0,0,0.2)',
        color: 'var(--text-main)',
        display: 'flex',
        flexDirection: 'column',
    },
    popupHeader: {
        backgroundColor: '#FF0000',
        color: 'white',
        padding: '15px 20px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTopLeftRadius: '12px',
        borderTopRightRadius: '12px',
    },
    popupTitle: {
        fontSize: '24px',
        fontWeight: 'bold',
    },
    closeButton: {
        background: 'none',
        border: 'none',
        cursor: 'pointer',
        color: 'white',
        padding: '5px',
    },
    popupContent: {
        padding: '30px',
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
    },
    inputGroup: {
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    label: {
        fontSize: '14px',
        fontWeight: '600',
    },
    input: {
        padding: '10px',
        borderRadius: '6px',
        border: '1px solid var(--border-color)',
        backgroundColor: 'var(--bg-main)',
        color: 'var(--text-main)',
        fontSize: '14px',
    },
    fileInput: {
        padding: '10px',
        border: '1px dashed var(--border-color)',
        borderRadius: '6px',
        backgroundColor: 'var(--bg-main)',
        color: 'var(--text-main)',
        cursor: 'pointer',
    },
    imagePreview: {
        marginTop: '10px',
        height: '100px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        border: '1px solid var(--border-color)',
        borderRadius: '6px',
        padding: '5px',
    },
    previewImg: {
        maxHeight: '100%',
        maxWidth: '100%',
        objectFit: 'contain',
    },
    popupActions: {
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '15px',
        marginTop: '10px',
    },
    resetButton: {
        padding: '10px 20px',
        borderRadius: '6px',
        border: '1px solid var(--border-color)',
        backgroundColor: 'transparent',
        color: 'var(--text-main)',
        cursor: 'pointer',
        fontWeight: '600',
    },
    submitButton: {
        padding: '10px 20px',
        borderRadius: '6px',
        border: 'none',
        backgroundColor: '#0044CC',
        color: 'white',
        cursor: 'pointer',
        fontWeight: '600',
    },
    pagination: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: '20px',
        marginBottom: '40px',
        gap: '10px',
    },
    pageBtn: {
        border: '1px solid var(--border-color)',
        backgroundColor: 'var(--bg-card)',
        color: 'var(--text-main)',
        padding: '5px 15px',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: '500',
        minWidth: '35px',
    },
    activePageBtn: {
        border: '1px solid #000',
        backgroundColor: 'black',
        color: 'white',
        padding: '5px 15px',
        borderRadius: '8px',
        cursor: 'pointer',
        fontWeight: '500',
        minWidth: '35px',
    },
    dots: {
        fontWeight: 'bold',
        letterSpacing: '2px',
        color: 'var(--text-main)',
    },
    sortDropdown: {
        position: 'absolute',
        top: '100%',
        right: 0,
        backgroundColor: 'var(--bg-card)',
        border: '1px solid var(--border-color)',
        borderRadius: '8px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
        zIndex: 100,
        minWidth: '150px',
        marginTop: '5px',
        padding: '5px 0',
    },
    sortSection: {
        padding: '5px 0',
    },
    sortLabel: {
        fontSize: '12px',
        fontWeight: '600',
        color: '#999',
        padding: '5px 15px',
        textTransform: 'uppercase',
    },
    sortOption: {
        padding: '8px 15px',
        fontSize: '14px',
        cursor: 'pointer',
        color: 'var(--text-main)',
        transition: 'background-color 0.2s',
    },
};

export default Products;
